### PR TITLE
Skip processing of ignored files during rebuild

### LINKED ISSUE #99: Goto Project Symbol or Reindexing causes an error
On Atom 1.12.7 and Goto 1.8.2, and using Goto Project Symbol (or reindexing) I get the following stacktrace:

```
Error: "toString()" failed
    at Buffer.toString (buffer.js:503:11)
    at Object.fs.readFileSync (fs.js:552:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at SymbolIndex.module.exports.SymbolIndex.processFile (/Users/dansisan/.atom/packages/goto/lib/symbol-index.coffee:154:15)
    at /Users/dansisan/.atom/packages/goto/lib/symbol-index.coffee:113:24
    at traverse (/Users/dansisan/.atom/packages/goto/node_modules/fs-plus/lib/fs-plus.js:419:13)
    at Object.traverseTreeSync (/Users/dansisan/.atom/packages/goto/node_modules/fs-plus/lib/fs-plus.js:424:14)
    at SymbolIndex.module.exports.SymbolIndex.rebuild (/Users/dansisan/.atom/packages/goto/lib/symbol-index.coffee:111:10)
    at atom-workspace.atom.commands.add.goto:rebuild-index (/Users/dansisan/.atom/packages/goto/lib/index.coffee:31:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

Goto File Symbol works fine.

### PR DESCRIPTION
**Pull request by dansisan**
This pull request fixes #99 and possibly other problems caused by processing "ignored" project files. In my case, a very large file apparently overflowed the buffer and crashed the project indexing.

The problem happens in `rebuild`: `traverseTreeSync` only checks `keepPath` on directories, not files, and so ignored files can still be processed.

### CODE REVIEW

File: lib/symbol-index.coffee [hunk 1]
```diff
@@ -103,7 +103,7 @@ class SymbolIndex
       @rebuild()
     else
       for fqn, symbols of @entries
-        if symbols is null and @keepPath(fqn)
+        if symbols is null
```
Comment (acusti) [inline lib/symbol-index.coffee]: Removing this check definitely seems right. `@keepPath` is supposed to be used to build the `@entries` cache, which obviates the need top check again on iterating over `@entries`.

File: lib/symbol-index.coffee [hunk 2]
```diff
@@ -150,6 +150,8 @@ class SymbolIndex
           matches.push(symbol)
 
   processFile: (fqn) ->
+    if not @keepPath(fqn)
```
Comment (acusti) [inline lib/symbol-index.coffee]: What would you think about just updating https://github.com/v3ss0n/goto/pull/102/files#diff-93954ac5275f714bda2fb60c4f378d2fR113 to `@processFile filePath if @keepPath filePath`? It would maintain the `@keepPath` checks in the same place during fs tree traversal and avoid duplicate work from calling `@processFile` on line 107.

**Review by acusti — CHANGES_REQUESTED** [review]
Thanks for this PR! Glad you uncovered this issue with only directories being checked. Just to confirm, this change will only fix cases where an offending file is git ignored (or ignored from the goto package settings), right? Either way, let’s get this fixed. Let me know what you think about my comment.

**Comment by dansisan** [comment]
Correct, it would only fix cases where an offending file fails keepPath.  If a user doesn't set a problem file as ignored in .gitignore or settings then this doesn't help.

**Review by dansisan — COMMENTED** [review]
@acusti I made the change you suggested.

**Review by acusti — APPROVED** [review]

**Comment by acusti** [comment]
Great thanks! Were you able to verify that this final version fixes your issue?

**Comment by acusti** [comment]
Fixes #99

**Comment by dansisan** [comment]
Yep, this fixes my issue. Go ahead and merge it.  Thanks!
